version: "3.8"

services:
  dev-container:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        IMAGE_VERSION: ${IMAGE_VERSION:-0.204.8}    # x, x.x, x.x.x
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}     # x, x.x
        DEBIAN_VERSION: ${DEBIAN_VERSION:-bullseye} # bullseye: Debian 11, buster: Debian 10
    command: sleep infinity
    volumes:
      - type: bind
        source: ~/.bashrc
        target: /home/vscode/.bashrc
        consistency: delegated
      - type: bind
        source: ~/.bash_aliases
        target: /home/vscode/.bash_aliases
        consistency: delegated
      - type: bind
        source: ~/.gitconfig
        target: /home/vscode/.gitconfig
        consistency: delegated
      - type: bind
        source: ../.home_directory/.bash_history
        target: /home/vscode/.bash_history
        consistency: delegated
      - type: bind
        source: ${HOST_WORKSPACE:-~/workspace}
        target: /home/vscode/workspace
        consistency: delegated
